# Generated by Django 4.2.26 on 2025-11-14 21:30

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del equipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('color', models.CharField(default='#FF0000', max_length=7, verbose_name='Color del equipo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team_avatars/', verbose_name='Avatar')),
                ('total_score', models.IntegerField(default=0, verbose_name='Puntuación total')),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Miembros')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-total_score', 'name'],
            },
        ),
    ]
