# Generated by Django 4.2.26 on 2025-11-14 22:17

from django.db import migrations, models
import secrets
import string


def generate_invite_codes(apps, schema_editor):
    """Generar códigos de invitación para equipos existentes"""
    Team = apps.get_model('teams', 'Team')
    used_codes = set()
    
    for team in Team.objects.all():
        while True:
            code = ''.join(secrets.choice(string.ascii_uppercase + string.digits) for _ in range(8))
            if code not in used_codes:
                used_codes.add(code)
                team.invite_code = code
                team.save()
                break


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Código de invitación'),
        ),
        migrations.RunPython(generate_invite_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='team',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, unique=True, verbose_name='Código de invitación'),
        ),
    ]
