# Generated by Django 4.2.26 on 2025-11-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTFConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mi CTF', max_length=200, verbose_name='Nombre del CTF')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Inicio del CTF')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin del CTF')),
                ('is_active', models.BooleanField(default=False, verbose_name='CTF Activo')),
            ],
            options={
                'verbose_name': 'Configuración CTF',
                'verbose_name_plural': 'Configuración CTF',
            },
        ),
    ]
