# Generated by Django 4.2.26 on 2025-11-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctfconfig',
            name='first_blood_points',
            field=models.IntegerField(default=50, verbose_name='Puntos de First Blood'),
        ),
        migrations.AddField(
            model_name='ctfconfig',
            name='timezone',
            field=models.CharField(default='America/Argentina/Buenos_Aires', max_length=100, verbose_name='Zona Horaria'),
        ),
    ]
