# Generated by Django 4.2.26 on 2025-11-15 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_team_invite_code'),
        ('scoreboard', '0002_ctfconfig_first_blood_points_ctfconfig_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código del Logro')),
                ('category', models.CharField(choices=[('team', 'Equipo'), ('individual', 'Individual')], default='team', max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Conseguido el')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='teams.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['-earned_at'],
                'unique_together': {('code', 'user'), ('code', 'team')},
            },
        ),
    ]
