# Generated by Django 4.2.26 on 2025-11-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctfconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo personalizado (.png, .ico, .jpg). Se mostrará en el navbar y como favicon.', null=True, upload_to='ctf_logos/', verbose_name='Logo del CTF'),
        ),
    ]
