# Generated by Django 4.2.26 on 2025-11-14 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('icon', models.CharField(default='🔐', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='#00FF00', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('points', models.IntegerField(default=100, verbose_name='Puntos')),
                ('flag', models.CharField(max_length=200, verbose_name='Flag')),
                ('files', models.FileField(blank=True, null=True, upload_to='challenge_files/', verbose_name='Archivos')),
                ('hints', models.TextField(blank=True, verbose_name='Pistas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='challenges.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['category', 'points'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_submitted', models.CharField(max_length=200, verbose_name='Flag enviada')),
                ('is_correct', models.BooleanField(default=False, verbose_name='¿Es correcta?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.challenge', verbose_name='Challenge')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teams.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FirstBlood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('achieved_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de logro')),
                ('bonus_points', models.IntegerField(default=50, verbose_name='Puntos bonus')),
                ('achieved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_bloods', to=settings.AUTH_USER_MODEL, verbose_name='Logrado por')),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_blood', to='challenges.challenge', verbose_name='Challenge')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_bloods', to='teams.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'First Blood',
                'verbose_name_plural': 'First Bloods',
                'ordering': ['-achieved_at'],
            },
        ),
    ]
